### ISSUE TITLE
MailMover incompatible with mbsync

### ISSUE THREAD

**Issue by dannyob** [teythoon/afew#95]
Mbsync/isync (a popular offline IMAP syncer) stores per-Maildir-folder UIDs by default in the filename of each message. When moving messages between folders, Afew keeps the filename of the message the same, which can result in UID clashes.

Mbsync can use an alternative UID system which gets around this problem, but it may make sense to generate new filenames (this might be complicated by the fact that many Maildir implementations also store mail flags in the filename). At the very least, we should probably warn against using afew with mbsync in this configuration.

**Comment by varac** [comment]
@pazz: can this get closed, looks like it's already solved by #91

**Comment by pazz** [comment]
@teythoon I think he means you :)
